host: "127.0.0.1"
port: 9900
pretty_json: true
endpoints:
  -
    path: "/info"
    methods:
      GET:
        type: "info"
        authorizers: ["custom"]
  -
    path: "/test"
    methods:
      GET:
        type: "shell"
        config:
          single_result: 0
          commands:
            -
              chdir: "/tmp"
              command: "cat out.out"
              format: "json"
  -
    path: "/multi"
    methods:
      GET:
        type: "multi"
        config:
          single_result: 0
          tasks:
            -
              type: "http"
              config:
                single_result: 0
                urls:
                  -
                    url: "http://www.google.com"
  -
    path: "/ip"
    raw_response: true
    methods:
      GET:
        type: "http"
        config:
          urls:
            -
              url: "http://ip.jsontest.com/"
              format: "json"
      POST:
        type: "http"
        config:
          urls:
            -
              url: "http://ip.jsontest.com/"
              format: "json"
              method: "GET"
  -
    path: "/postgres/{id:[0-9]+}"
    methods:
      GET:
        type: "postgres"
        config:
          return_queries: true
          queries:
            -
              url: "postgres://user:pass@localhost/test"
              query: "SELECT * FROM auth_user WHERE id = $1"
              args:
                - "{{.url.id}}"
  -
    path: "/redis/{id:[0-9]+}"
    methods:
      GET:
        type: "redis"
        config:
          database: 1
          return_queries: true
          queries:
            -
              command: "GET"
              args:
                - "aaaa"
              type: "string"
  -
    path: "/mysql/{id:[0-9]+}"
    methods:
      GET:
        type: "mysql"
        config:
          return_queries: true
          queries:
            -
              url: "user:password@tcp(127.0.0.1:3306)/database"
              query: "SELECT * FROM auth_user WHERE id = ?"
              args:
                - "{{.url.id}}"
  -
    path: "/file/some"
    methods:
      GET:
        type: "filesystem"
        config:
          file: "/tmp/file"
  -
    path: "/static/{file:.+}"
    methods:
      GET:
        type: "filesystem"
        config:
          file: "{{.url.file}}"
          output: "{{.query.output}}"
          directory: "/tmp"
          index: true
authorizers:
  basic:
    type: "basic"
    config:
      username: "hello"
      password: "world"
  custom:
    type: "http"
    config:
      url: "http://localhost:8080/"
      data: '{"user": "{{.username}}", "password": "{{.password}}"}'
